[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15"
reqewest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
common = { path = "../common" }
